Repository sgdevcamp2022/recoder, pull requests merged in 2023-02, with the labels that each got.

#43 [SERVER] Feature/#41 시그널링 서버 리팩토링
  .DS_Store
  backend/.DS_Store
  backend/signalling/.DS_Store
  backend/signalling/.gitignore
  backend/signalling/README.md
  backend/signalling/api/join/join.js
  backend/signalling/api/meeting/meeting.js
  backend/signalling/api/swagger.json
  backend/signalling/controller/room_controller.js
  backend/signalling/index.js
  backend/signalling/models/url_model.js
  backend/signalling/package.json
  backend/signalling/src/.DS_Store
  backend/signalling/src/Host.js
  backend/signalling/src/Server.js
  backend/signalling/src/ServerApi.js
  backend/signalling/src/config.js
Labels: refactor 🔨

#47 [APP] Feature/#33 waiting video and audio 대기실 카메라 & 오디오 출력
  client-android/app/src/main/AndroidManifest.xml
  client-android/buildSrc/src/main/kotlin/Dependencies.kt
  client-android/gradle.properties
  client-android/gradle/wrapper/gradle-wrapper.properties
  client-android/presentation/build.gradle.kts
  client-android/presentation/src/main/java/com/recoder/presentation/ui/MainActivity.kt
  client-android/presentation/src/main/java/com/recoder/presentation/ui/waiting/WaitingRoomFragment.kt
  client-android/presentation/src/main/res/drawable/waiting_camera_toggle_button.xml
  client-android/presentation/src/main/res/drawable/waiting_mic_toggle_button.xml
  client-android/presentation/src/main/res/layout/fragment_waiting_room.xml
  client-android/presentation/src/main/res/layout/video_base.xml
  client-android/presentation/src/main/res/layout/video_container.xml
  client-android/presentation/src/main/res/navigation/home_nav_graph.xml
  client-android/presentation/src/main/res/values/strings.xml
Labels: feat ✨

#56 [SERVER] Feature/#41 사용하지 않는 함수 제거
  .gitignore_global
  backend/signalling/src/Peer.js
  backend/signalling/src/Room.js
  backend/signalling/src/Server.js
Labels: refactor 🔨

#57 [SERVER] Feature/#42 유저 서버 세팅
  backend/auth/.gitignore
  backend/auth/controller/testController.js
  backend/auth/index.js
  backend/auth/package-lock.json
  backend/auth/package.json
  backend/auth/service/testService.js
Labels: refactor 🔨

#58 [SERVER] Feature/#45 유저 로그인/회원가입 및 CRUD
  backend/auth/controller/index.js
  backend/auth/controller/testController.js
  backend/auth/controller/userController.js
  backend/auth/index.js
  backend/auth/models/userModel.js
  backend/auth/package-lock.json
  backend/auth/package.json
  backend/auth/service/mailService.js
  backend/auth/service/testService.js
Labels: feat ✨

#61 [APP] Feature/#52 rest api connect
  client-android/app/src/main/java/com/recoder/comeet/di/NetworkModule.kt
  client-android/buildSrc/src/main/kotlin/Dependencies.kt
  client-android/data/build.gradle.kts
  client-android/data/src/main/java/com/recoder/data/di/ApiModule.kt
  client-android/data/src/main/java/com/recoder/data/di/NetworkModule.kt
  client-android/data/src/main/java/com/recoder/data/di/RepositoryModule.kt
  client-android/data/src/main/java/com/recoder/data/network/MeetingApi.kt
  client-android/data/src/main/java/com/recoder/data/network/handleApi.kt
  client-android/data/src/main/java/com/recoder/data/repository/MeetingRepositoryImpl.kt
  client-android/domain/src/main/java/com/recoder/domain/repository/MeetingRepository.kt
  client-android/domain/src/main/java/com/recoder/domain/usecase/CreateLinkUseCase.kt
Labels: feat ✨

#67 [SERVER] Feature/#64 소켓 버그 수정
  backend/signalling/src/Server.js
Labels: bug 🐞

#68 [SERVER] Feature/#59 인증 구현
  backend/auth/.gitignore
  backend/auth/controller/index.js
  backend/auth/controller/userController.js
  backend/auth/models/authModel.js
  backend/auth/package-lock.json
  backend/auth/package.json
  backend/auth/service/mailService.js
  backend/auth/service/template.ejs
  backend/auth/service/userService.js
Labels: feat ✨

#74 [SERVER] Feature/#72 join 참가자 정보 리턴 형식 변경
  backend/signalling/src/Room.js
Labels: bug 🐞

#79 [SERVER] Feature/#63 참가 권한
  backend/signalling/src/Peer.js
  backend/signalling/src/Room.js
  backend/signalling/src/Server.js
  client-android/presentation/src/main/java/com/recoder/presentation/ui/home/HomeFragment.kt
Labels: feat ✨

#88 [SERVER] Feature/#87 join 반환 형식 수정
  backend/signalling/src/Room.js
Labels: refactor 🔨

#90 [SERVER] Feature/#89 새로운 참가자 알림
  backend/signalling/src/Server.js
Labels: bug 🐞

#94 [SERVER] Feature/#93 논의사항 수정
  backend/signalling/src/Room.js
  backend/signalling/src/Server.js
Labels: refactor 🔨

#98 [SERVER] Feature/#97 disconnect 통합
  backend/signalling/src/Server.js
Labels: bug 🐞
